# Generated by Django 2.1.7 on 2019-06-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_code', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('depart', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('week_day', models.CharField(max_length=50)),
                ('time', models.IntegerField()),
                ('room', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('required', models.BooleanField()),
                ('credit', models.IntegerField()),
                ('division', models.CharField(max_length=50)),
                ('classes', models.IntegerField()),
            ],
        ),
    ]
