# Generated by Django 2.1.7 on 2019-07-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='syllabus',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
