# Generated by Django 2.1.7 on 2019-07-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_auto_20190703_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='content',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='syllabus',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
